<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="2" failures="0" skipped="0" tests="2" time="21.900" timestamp="2021-02-25T18:39:36.649256" hostname="barrachina-SONDRA"><testcase classname="" name="tests.test_custom_layers" time="0.000"><error message="collection failure">ImportError while importing test module '/home/barrachina/Documents/cvnn/tests/test_custom_layers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/envs/cvnn-develop/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_custom_layers.py:7: in &lt;module&gt;
    import tensorflow_datasets as tfds
E   ModuleNotFoundError: No module named 'tensorflow_datasets'</error></testcase><testcase classname="" name="tests.test_several_datasets" time="0.000"><error message="collection failure">ImportError while importing test module '/home/barrachina/Documents/cvnn/tests/test_several_datasets.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../anaconda3/envs/cvnn-develop/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_several_datasets.py:3: in &lt;module&gt;
    import tensorflow_datasets as tfds
E   ModuleNotFoundError: No module named 'tensorflow_datasets'</error></testcase></testsuite></testsuites>